INPUT:
  FOLDER : "../SKU110K_fixed/"
  MAX_SIZE_TRAIN : 1333
MODEL:
  NUM_CLASSES: 2
DATASETS:
  TRAIN : "SKU110K_train"
  TEST : "SKU110K_test"

SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 2
DATALOADER:
  NUM_WORKERS : 0
TEST:
  IMS_PER_BATCH: 2

OUTPUT_DIR: "./outputs/retinanet"