INPUT:
  FOLDER : "../SKU110K_fixed/"
MODEL:
  NUM_CLASSES: 2
  WEIGHT: "./retinanet_rn50fpn/retinanet_rn50fpn.pth"
DATASETS:
  TRAIN : "SKU110K_train"
  TEST : "SKU110K_test"

SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 2
DATALOADER:
  NUM_WORKERS : 0
TEST:
  IMS_PER_BATCH: 2

OUTPUT_DIR: "./outputs/retinanet"